#define HAVE_MALLOC_H 1
#define ARCH_X86 1
#define SYS_LINUX 1
#define HAVE_LOG2F 1
#define fseek fseeko
#define ftell ftello
#define CHROMA_FORMAT CHROMA_420
#define HAVE_GPL 1
#define HAVE_BEOSTHREAD 0
#define HAVE_POSIXTHREAD 0
#define HAVE_WIN32THREAD 0
#define HAVE_THREAD 0
#define HAVE_VISUALIZE 0
#define HAVE_CPU_COUNT 0
